#!/usr/bin/env bash
# build4.sh — complete build of the SONiC gNMI telemetry lab image (fixes build3's 4 cgo blockers).
#
# Supersedes build3.sh. build3 resolved: (a) rsync, (b) unbound rc, (c) swig include path,
# (d) full CVL schema (145 yin, CVL_SCHEMA_OK), (e) pyang 2.7.1 leafref patch.
# build3 FAILED at `make` in sonic-gnmi with exactly four missing dependencies:
#
#   (f) security/pam_appl.h  — vendor/github.com/msteinert/pam cgo  -> apt libpam0g-dev
#   (g) libyang/libyang.h    — vendor/.../cvl/internal/util cgo     -> trixie libyang-dev 3.12.2-1
#       (the pinned image ships the EXACT same Debian package: libyang3 3.12.2-1,
#        /lib/x86_64-linux-gnu/libyang.so.3.9.1; the cgo surface is only the stable
#        logging API: ly_set_log_clb (5-arg), ly_log_level, LY_LLDBG/LY_LLERR — verified
#        against the trixie header. We link against the image's own libyang.so.3.9.1.)
#   (h) ocbinds Device/SchemaTree/Unmarshal — generated by the ygot generator from the
#       sonic-mgmt-common YANG tree: make go-deps + make -C translib ocbinds/ocbinds.go
#       (the go.mod replace => ../sonic-mgmt-common makes `go mod vendor` in sonic-gnmi
#       pick the generated file up on the clean rebuild).
#   (i) cfg_schema.h         — generated by sonic-swss-common@240a31a gen_cfg_schema.py,
#       executed INSIDE the pinned image (sonic_yang python module + /usr/local/yang-models
#       are present there; verified: 246 CFG_* table macros).
#
# Output: localhost:5000/sonic-vs-gnmi:202605 (separate repo — the in-flight provision
# cycles pin localhost:5000/sonic-vs:202605@sha256:097d1551… and must not be disturbed).
# Re-pinning versions.lock.yaml + lab/topology.clab.yml to the new name@digest happens only
# after this image passes the unchanged capability gate.
set -uo pipefail

BASE=/root/ainetops-demo/.wiggum/features/001-ainetops-sonic-evpn-fabric/build-gnmi
SRC=$BASE/src
LIBS=$BASE/libs
LOG=${1:-$BASE/build4.log}
IMAGENAME=localhost:5000/sonic-vs-gnmi
TAG=202605
PINNED=localhost:5000/sonic-vs:202605@sha256:097d1551398223969624a8095b37e60351b1629845c1e62e1f437decc1fb873b

log() { echo "[build4] $*" | tee -a "$LOG"; }
fail() { log "FAILED: $*"; exit 1; }

export DOCKER_BUILDKIT=0

# --- 1. Source checkouts at the exact pinned commits -------------------------
if [[ ! -d $SRC/sonic-gnmi/.git ]]; then
  log "cloning sonic-gnmi"
  git clone -q https://github.com/sonic-net/sonic-gnmi.git $SRC/sonic-gnmi || fail "clone sonic-gnmi"
fi
( cd $SRC/sonic-gnmi && git checkout -q dd99be1841ca172dfac2fa7842afeeb5e532766c ) \
  || fail "checkout sonic-gnmi@dd99be18"
( cd $SRC/sonic-gnmi && git clean -qfdx 2>/dev/null || true )
( cd $SRC/sonic-gnmi && git checkout -q -- . 2>/dev/null || true )

if [[ ! -d $SRC/sonic-mgmt-common/.git ]]; then
  log "cloning sonic-mgmt-common"
  git clone -q https://github.com/sonic-net/sonic-mgmt-common.git $SRC/sonic-mgmt-common || fail "clone sonic-mgmt-common"
fi
( cd $SRC/sonic-mgmt-common && git checkout -q cdb612efcf6835f8dc3f004e214440ed8b744644 ) \
  || fail "checkout sonic-mgmt-common@cdb612e"
( cd $SRC/sonic-mgmt-common && git clean -qfdx 2>/dev/null || true )
( cd $SRC/sonic-mgmt-common && git checkout -q -- . 2>/dev/null || true )
# Build-tool patch: robust leafref handling for pyang 2.7.1 (build3 (e))
( cd $SRC/sonic-mgmt-common && git apply --whitespace=nowarn --check "$BASE/patches/generate_yin_pyang271.patch" ) 2>/dev/null \
  || ( cd $SRC/sonic-mgmt-common && git apply --whitespace=nowarn "$BASE/patches/generate_yin_pyang271.patch" ) \
  || fail "apply generate_yin patch"

( cd $SRC/sonic-swss-common && git checkout -q 240a31aacc28291de869f9583e2ed22aa8b620cc ) \
  || fail "checkout sonic-swss-common@240a31a"

# --- 2. Runtime libs + cvlyang set from the pinned image ---------------------
mkdir -p $LIBS $BASE/cvlyang
if [[ ! -f $LIBS/libswsscommon.so.0.0.0 || ! -f $LIBS/libhiredis.so.0.14 || ! -f $BASE/cvlyang/sonic-srv6.yang || ! -f $LIBS/libyang.so.3.9.1 ]]; then
  log "extracting runtime libs + cvlyang set from pinned image (via temp container)"
  docker rm -f ainetops-gnmi-libs >/dev/null 2>&1 || true
  docker create --name ainetops-gnmi-libs $PINNED >/dev/null || fail "create libs container"
  docker cp ainetops-gnmi-libs:/lib/x86_64-linux-gnu/libswsscommon.so.0.0.0 $LIBS/ \
    || fail "copy libswsscommon"
  [[ -f $LIBS/libhiredis.so.0.14 ]] || \
    { docker cp ainetops-gnmi-libs:/lib/x86_64-linux-gnu/libhiredis.so.0.14 $LIBS/ \
        || fail "copy libhiredis"; }
  [[ -f $LIBS/libyang.so.3.9.1 ]] || \
    { docker cp ainetops-gnmi-libs:/lib/x86_64-linux-gnu/libyang.so.3.9.1 $LIBS/ \
        || fail "copy libyang"; }
  rm -rf $BASE/cvlyang && mkdir -p $BASE/cvlyang
  docker cp ainetops-gnmi-libs:/usr/local/cvlyang-models/. $BASE/cvlyang/ \
    || fail "copy cvlyang-models"
  docker rm ainetops-gnmi-libs >/dev/null 2>&1 || true
fi
ln -sf libswsscommon.so.0.0.0 $LIBS/libswsscommon.so.0
ln -sf libswsscommon.so.0 $LIBS/libswsscommon.so
ln -sf libhiredis.so.0.14 $LIBS/libhiredis.so
ln -sf libyang.so.3.9.1 $LIBS/libyang.so
# (g) libyang headers: trixie libyang-dev 3.12.2-1 == image's libyang3 3.12.2-1
[[ -f $BASE/debs/x-dev/usr/include/libyang/libyang.h ]] || \
  fail "libyang-dev headers missing (debs/x-dev/usr/include/libyang/libyang.h)"

# --- 3. Build container (reused when alive) -----------------------------------
CONT=ainetops-gnmi-build
if docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$CONT"; then
  log "reusing live build container $CONT"
else
  docker rm -f $CONT >/dev/null 2>&1 || true
  log "creating build container (debian:bookworm)"
  docker run -d --name $CONT \
    -v $SRC:/src -v $LIBS:/libs -v $BASE/stage:/stage -v $BASE/cvlyang:/cvlyang \
    -v $BASE/debs/x-dev/usr/include/libyang:/libyang-include:ro \
    debian:bookworm sleep 96h >/dev/null || fail "docker run build container"
fi

rcnt() { docker exec $CONT bash -c "$1" 2>&1 | tee -a "$LOG"; }

# Ensure /cvlyang is present in the container (mounted on fresh create, or
# copied in when reusing a pre-existing container that lacks the mount).
rcnt "ls /cvlyang/sonic-srv6.yang >/dev/null 2>&1" || { log "copying cvlyang set into build container"; docker cp $BASE/cvlyang/. $CONT:/cvlyang/ || fail "copy cvlyang into container"; }
# (g) libyang headers into the build container, under a libyang/ subdir so
# `#include <libyang/libyang.h>` resolves (mount on fresh create, copy when reusing)
rcnt "ls /libyang-include/libyang.h >/dev/null 2>&1" || { log "copying libyang headers into build container"; docker cp $BASE/debs/x-dev/usr/include/libyang/. $CONT:/opt/libyang-include-libyang-tmp/ || fail "copy libyang headers"; }
rcnt "set -e; rm -rf /opt/libyang-include; mkdir -p /opt/libyang-include/libyang; if [ -d /libyang-include ]; then cp -r /libyang-include/. /opt/libyang-include/libyang/; elif [ -d /opt/libyang-include-libyang-tmp ]; then cp -r /opt/libyang-include-libyang-tmp/. /opt/libyang-include/libyang/; rm -rf /opt/libyang-include-libyang-tmp; else false; fi; ls /opt/libyang-include/libyang/libyang.h /opt/libyang-include/libyang/log.h" || fail "stage libyang headers"

log "installing build tools (+ libpam0g-dev (f), boost/hiredis/uuid/zmq/lua for swsscommon wrap)"
rcnt "export DEBIAN_FRONTEND=noninteractive; if command -v rsync >/dev/null && command -v swig >/dev/null && command -v git >/dev/null && command -v patch >/dev/null && command -v protoc >/dev/null && command -v gcc >/dev/null && ls /usr/include/security/pam_appl.h /usr/include/boost/functional/hash.hpp /usr/include/boost/serialization/vector.hpp /usr/include/hiredis/hiredis.h /usr/include/uuid/uuid.h /usr/include/zmq.h /usr/include/pcre2.h >/dev/null 2>&1; then echo TOOLS_OK-CACHED; else apt-get update -qq && apt-get install -y -qq --no-install-recommends build-essential swig python3-pip ca-certificates curl rsync patch git protobuf-compiler libpam0g-dev libpcre2-dev libboost-dev libboost-serialization-dev libhiredis-dev uuid-dev libzmq3-dev liblua5.4-dev >/dev/null && echo TOOLS_OK; fi" \
  || fail "apt install build tools"
rcnt "gcc --version | head -1; swig -version | sed -n 2p; protoc --version; ls /usr/include/security/pam_appl.h /usr/include/boost/serialization/vector.hpp /usr/include/hiredis/hiredis.h /usr/include/uuid/uuid.h /usr/include/zmq.h"

log "installing Go 1.25.9"
rcnt "set -e; if [ ! -x /usr/local/go/bin/go ]; then curl -fsSL https://go.dev/dl/go1.25.9.linux-amd64.tar.gz -o /tmp/go.tgz && tar -C /usr/local -xzf /tmp/go.tgz; fi; /usr/local/go/bin/go version" \
  || fail "install go"

log "installing pyang"
rcnt "python3 -c 'import pyang' 2>/dev/null || pip3 install --no-cache-dir --break-system-packages pyang jinja2 >/dev/null 2>&1; python3 -c 'import pyang; print(\"pyang\", pyang.__version__)'" \
  || fail "install pyang"

log "staging swss-common headers + swig interface (pinned 240a31a)"
rcnt "set -e; rm -rf /opt/swss-include /opt/swss-i; mkdir -p /opt/swss-include /opt/swss-i; cp -r /src/sonic-swss-common/common/. /opt/swss-include/; cp /src/sonic-swss-common/goext/swsscommon.i /opt/swss-i/swsscommon.i; ls /opt/swss-include | wc -l" \
  || fail "stage swss headers"

# --- 2b (i). cfg_schema.h generated INSIDE the pinned image -------------------
log "generating cfg_schema.h inside pinned image (gen_cfg_schema.py @ 240a31a)"
docker rm -f ainetops-cfgschema >/dev/null 2>&1 || true
docker run -d --name ainetops-cfgschema \
  -v $SRC/sonic-swss-common:/swss:ro --entrypoint python3 $PINNED \
  /swss/gen_cfg_schema.py -o /tmp/cfg_schema.h >/dev/null \
  || fail "run gen_cfg_schema.py in image"
# give the short-lived container a moment, then collect the artifact
sleep 5
rm -f /tmp/cfg_schema.h.host
docker cp ainetops-cfgschema:/tmp/cfg_schema.h /tmp/cfg_schema.h.host 2>/dev/null \
  || { docker logs ainetops-cfgschema 2>&1 | tail -5; docker rm -f ainetops-cfgschema >/dev/null 2>&1; fail "copy cfg_schema.h out"; }
docker rm -f ainetops-cfgschema >/dev/null 2>&1 || true
grep -q "define CFG_" /tmp/cfg_schema.h.host || fail "cfg_schema.h has no CFG_ macros"
CFGTABLES=$(grep -c "define CFG_" /tmp/cfg_schema.h.host)
log "cfg_schema.h: $CFGTABLES table macros"
docker cp /tmp/cfg_schema.h.host $CONT:/opt/swss-include/cfg_schema.h || fail "copy cfg_schema.h into build container"

# --- 4. sonic-mgmt-common: yang tree (protobuf input) -------------------------
log "building sonic-mgmt-common yang tree"
rcnt "set -e; cd /src/sonic-mgmt-common; if [ ! -d build/yang ]; then make -C models/yang > /tmp/mgmt-yang.log 2>&1 || { tail -30 /tmp/mgmt-yang.log; exit 1; }; fi; ls build/yang | head -5" \
  || fail "mgmt-common yang tree"

# --- 4b. Full CVL schema from the image's cvlyang set (build3 result reused) ---
if rcnt "test -f /tmp/cvl-schema/sonic-srv6.yin && test -f /tmp/cvl-schema/sonic-telemetry.yin && test -f /tmp/cvl-schema/sonic-bgp-global.yin && test \$(ls /tmp/cvl-schema/*.yin | wc -l) -ge 140 && echo CVL_SCHEMA_OK-CACHED" | grep -q CVL_SCHEMA_OK-CACHED; then
  log "reusing existing CVL schema (/tmp/cvl-schema)"
else
  log "compiling full CVL schema (144 modules) to .yin"
  rcnt "cd /src/sonic-mgmt-common/cvl; rm -rf /tmp/cvl-schema; mkdir -p /tmp/cvl-schema; python3 tools/generate_yin.py --path=/cvlyang --path=/src/sonic-mgmt-common/build/yang --path=/src/sonic-mgmt-common/build/yang/common --path=/src/sonic-mgmt-common/build/yang/extensions --out-dir=/tmp/cvl-schema > /tmp/cvl-gen.log 2>&1; rc=\$?; tail -12 /tmp/cvl-gen.log; echo GEN_EXIT=\$rc; ls /tmp/cvl-schema | wc -l" \
    || { rcnt "tail -30 /tmp/cvl-gen.log"; fail "cvl schema generation"; }
  rcnt "test -f /tmp/cvl-schema/sonic-srv6.yin && test -f /tmp/cvl-schema/sonic-telemetry.yin && test -f /tmp/cvl-schema/sonic-bgp-global.yin && test \$(ls /tmp/cvl-schema/*.yin | wc -l) -ge 140 && echo CVL_SCHEMA_OK" \
    || fail "CVL schema missing required modules"
fi

# --- 4c (h). ocbinds: ygot generator produces ocbinds/ocbinds.go ---------------
log "generating ocbinds/ocbinds.go (ygot) in sonic-mgmt-common"
rcnt "set -e; export PATH=/usr/local/go/bin:\$PATH; cd /src/sonic-mgmt-common; make go-deps > /tmp/mgmt-godeps.log 2>&1 || { tail -30 /tmp/mgmt-godeps.log; exit 1; }; echo MGMT_GO_DEPS_OK" \
  || fail "mgmt-common go-deps"
rcnt "set -e; export PATH=/usr/local/go/bin:\$PATH; cd /src/sonic-mgmt-common; make -C translib ocbinds/ocbinds.go > /tmp/ocbinds.log 2>&1 || { tail -40 /tmp/ocbinds.log; exit 1; }; test -s translib/ocbinds/ocbinds.go && grep -q 'Device struct' translib/ocbinds/ocbinds.go && grep -q 'SchemaTree' translib/ocbinds/ocbinds.go && grep -q 'func Unmarshal' translib/ocbinds/ocbinds.go && wc -l translib/ocbinds/ocbinds.go" \
  || fail "ocbinds generation"

# --- 5. sonic-gnmi: patch Makefiles, clean rebuild -----------------------------
log "patching sonic-gnmi Makefiles for build container layout"
rcnt "set -e; cd /src/sonic-gnmi; sed -i 's|export CGO_CXXFLAGS := -I/usr/include/swss -w -Wall -fpermissive|export CGO_CXXFLAGS := -I/opt/swss-include -w -Wall -fpermissive|' Makefile; sed -i 's|export CGO_LDFLAGS := -lswsscommon -lhiredis|export CGO_LDFLAGS := -L/libs -lswsscommon -lhiredis -lzmq -Wl,-rpath,/lib/x86_64-linux-gnu|' Makefile; sed -i 's|-I/usr/include/swss/|-I/opt/swss-include/|' swsscommon/Makefile; grep -n 'CGO_CXXFLAGS\|CGO_LDFLAGS' Makefile | head -4" \
  || fail "patch Makefiles"

log "clean rebuild of sonic-gnmi (fresh vendor so ocbinds.go is re-vendored)"
rcnt "set -e; export PATH=/usr/local/go/bin:\$PATH; export CGO_ENABLED=1; export CGO_CFLAGS='-I/opt/libyang-include'; export LD_LIBRARY_PATH=/libs; mkdir -p /usr/share/swss; cp /opt/swss-i/swsscommon.i /usr/share/swss/swsscommon.i; cd /src/sonic-gnmi; rm -rf vendor build; rc=0; make > /tmp/make4.log 2>&1 || rc=\$?; tail -60 /tmp/make4.log; exit \$rc" \
  || { log "sonic-gnmi build failed; dumping logs"; rcnt "cd /src/sonic-gnmi; tail -80 /tmp/make4.log 2>/dev/null; ls build 2>/dev/null"; fail "sonic-gnmi"; }

log "verifying telemetry binary linkage"
rcnt "set -e; cd /src/sonic-gnmi; test -x build/bin/telemetry || ls build/bin; ldd build/bin/telemetry | grep -E 'swsscommon|hiredis|yang|not found' || true"

# --- 6. Assemble the updated image ---------------------------------------------
log "assembling updated image ($IMAGENAME:$TAG)"
STAGE=$BASE/stage
rm -rf $STAGE/*; mkdir -p $STAGE
cp $SRC/sonic-gnmi/build/bin/telemetry $STAGE/telemetry
mkdir -p $STAGE/schema
rcnt "cp /tmp/cvl-schema/*.yin /stage/schema/ && ls /stage/schema | wc -l" || fail "stage schema"
cp $BASE/telemetry.service.sh $STAGE/telemetry.sh
cp $BASE/telemetry.conf $STAGE/telemetry.conf
cat > $STAGE/Dockerfile <<EOF
FROM $PINNED
COPY telemetry /usr/sbin/telemetry
COPY schema /usr/sbin/schema
COPY telemetry.sh /usr/bin/telemetry.sh
COPY telemetry.conf /etc/supervisor/conf.d/telemetry.conf
RUN chmod +x /usr/sbin/telemetry /usr/bin/telemetry.sh && \\
    ldd /usr/sbin/telemetry | grep -E 'swsscommon|hiredis|yang' || true
EOF
( cd $STAGE && docker build -q -t $IMAGENAME:$TAG . ) 2>&1 | tee -a "$LOG" || fail "docker build"

NEWDIGEST=$(docker image inspect --no-trunc $IMAGENAME:$TAG --format '{{.RepoDigests}}' 2>/dev/null | head -1)
[[ -z $NEWDIGEST ]] && NEWDIGEST=$(docker image inspect --no-trunc $IMAGENAME:$TAG --format '{{.Id}}')
log "new image digest: $NEWDIGEST"
echo "$NEWDIGEST" > $BASE/image-digest.txt.new

# --- 7. Smoke test (bridge network: no host-port conflicts with in-flight cycles)
log "smoke testing telemetry service in new image"
docker rm -f ainetops-gnmi-smoke >/dev/null 2>&1 || true
docker run -d --name ainetops-gnmi-smoke $IMAGENAME:$TAG >/dev/null || fail "smoke run"
sleep 90
log "smoke: supervisord + telemetry status"
docker exec ainetops-gnmi-smoke bash -c 'supervisorctl status 2>&1 | grep -E "telemetry|redis-server|start.sh" || true; echo ---; tail -25 /var/log/telemetry-err.log 2>/dev/null || true; echo ---; (command -v ss >/dev/null && ss -ltn | grep 8080) || (netstat -ltn 2>/dev/null | grep 8080) || echo "port 8080 not listening yet"' | tee -a "$LOG"

log "BUILD COMPLETE"
