apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ainetops-sonic-provider
subjects:
- kind: ServiceAccount
  name: ainetops-sonic-provider
  namespace: ainetops-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ainetops-sonic-provider
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ainetops-srv6-controller
subjects:
- kind: ServiceAccount
  name: ainetops-srv6-controller
  namespace: ainetops-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ainetops-srv6-controller
