apiVersion: v1
kind: ServiceAccount
metadata:
  name: ainetops-sonic-provider
  namespace: ainetops-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ainetops-srv6-controller
  namespace: ainetops-system
