//go:build !ignore_autogenerated

// Code generated by hand to satisfy runtime.Object without full codegen.
// DO NOT EDIT lightly; keep in sync with srv6service_types.go.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of this object into another object of the
// same type that is provided as a argument.
func (in *SRv6Service) DeepCopyInto(out *SRv6Service) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SRv6Service.
func (in *SRv6Service) DeepCopy() *SRv6Service {
	if in == nil {
		return nil
	}
	out := new(SRv6Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *SRv6Service) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SRv6ServiceList.
func (in *SRv6ServiceList) DeepCopyInto(out *SRv6ServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SRv6Service, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a new SRv6ServiceList by deep copying the receiver.
func (in *SRv6ServiceList) DeepCopy() *SRv6ServiceList {
	if in == nil {
		return nil
	}
	out := new(SRv6ServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object for SRv6ServiceList.
func (in *SRv6ServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for SRv6ServiceSpec.
func (in *SRv6ServiceSpec) DeepCopyInto(out *SRv6ServiceSpec) {
	*out = *in
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]Attachment, len(*in))
		copy(*out, *in)
	}
	if in.TransitWaypoints != nil {
		in, out := &in.TransitWaypoints, &out.TransitWaypoints
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for SRv6ServiceStatus.
func (in *SRv6ServiceStatus) DeepCopyInto(out *SRv6ServiceStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
	if in.ConfigHashes != nil {
		in, out := &in.ConfigHashes, &out.ConfigHashes
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}
