[program:telemetry]
command=/usr/bin/telemetry.sh
priority=100
autostart=true
autorestart=true
startretries=100
startsecs=1
stdout_logfile=/var/log/telemetry.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile=/var/log/telemetry-err.log
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2
