apiVersion: v1
kind: Pod
metadata:
  name: gnmi-incluster-check-abcde
  namespace: ainetops-system
status:
  phase: Succeeded
  containerStatuses:
  - name: gnmic
    ready: true
    state:
      terminated:
        reason: Completed
        exitCode: 0
